using MediatR;
using GeneratorService.Infrastructure.AI;

namespace GeneratorService.Application.Features.GenerateWebsite;

/// <summary>
/// Handler for GenerateWebsiteCommand
/// Orchestrates AI-based website generation
/// </summary>
public class GenerateWebsiteHandler : IRequestHandler<GenerateWebsiteCommand, GenerateWebsiteResponse>
{
    private readonly ILlamaService _llamaService;
    private readonly IPromptBuilder _promptBuilder;
    private readonly IHtmlTemplateBuilder _templateBuilder;

    public GenerateWebsiteHandler(
        ILlamaService llamaService,
        IPromptBuilder promptBuilder,
        IHtmlTemplateBuilder templateBuilder)
    {
        _llamaService = llamaService;
        _promptBuilder = promptBuilder;
        _templateBuilder = templateBuilder;
    }

    public async Task<GenerateWebsiteResponse> Handle(GenerateWebsiteCommand request, CancellationToken cancellationToken)
    {
        string aiResponse;
        
        try
        {
            // Build AI prompt
            var prompt = _promptBuilder
                .SetContext($"Create a professional website for a {request.Industry} business")
                .SetTask($"Generate HTML, CSS, and JavaScript for a website called '{request.ProjectName}'")
                .AddConstraint($"Description: {request.Description}")
                .AddConstraint($"Color scheme: {request.ColorScheme}")
                .AddConstraint($"Features: {string.Join(", ", request.Features)}")
                .SetFormat("Return as structured HTML, CSS, and JavaScript")
                .Build();

            // Generate content via AI
            aiResponse = await _llamaService.GenerateTextAsync(prompt, cancellationToken);
        }
        catch (Exception ex) when (ex.InnerException?.Message.Contains("Connection refused") ?? false)
        {
            // Ollama not available - return demo/template content
            aiResponse = GenerateDemoContent(request);
        }

        // Build HTML template
        var htmlContent = _templateBuilder
            .SetPageTitle(request.ProjectName)
            .SetMetaDescription(request.Description)
            .AddBodyContent(GenerateHtmlBody(request, aiResponse))
            .BuildHtml();

        return new GenerateWebsiteResponse
        {
            ProjectId = Guid.NewGuid(),
            ProjectName = request.ProjectName,
            HtmlContent = htmlContent,
            CssContent = GenerateDemoCss(request),
            JsContent = _templateBuilder.BuildJs(),
            GeneratedAt = DateTime.UtcNow,
            Status = "Success"
        };
    }

    private string GenerateDemoContent(GenerateWebsiteCommand request)
    {
        return $@"
[DEMO MODE - Ollama Not Available]
Project: {request.ProjectName}
Type: {request.Industry}
Style: {request.ColorScheme}

This is a demonstration template generated for {request.ProjectName}.
Features: {string.Join(", ", request.Features ?? new List<string>())}";
    }

    private string GenerateHtmlBody(GenerateWebsiteCommand request, string aiResponse)
    {
        var features = request.Features?.Any() == true 
            ? string.Join("", request.Features.Select(f => $"<li>{f}</li>"))
            : "<li>Professional Design</li><li>Responsive Layout</li><li>Contact Form</li>";

        return $@"
<header style='background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 60px 20px; color: white; text-align: center;'>
  <h1 style='margin: 0; font-size: 2.5em;'>{request.ProjectName}</h1>
  <p style='margin: 10px 0 0 0; font-size: 1.2em;'>{request.Description}</p>
</header>

<section style='max-width: 1200px; margin: 40px auto; padding: 0 20px;'>
  <h2>Features</h2>
  <ul style='list-style: none; padding: 0;'>
    {features}
  </ul>
</section>

<section style='background: #f7fafc; padding: 40px 20px; text-align: center;'>
  <h2>Get Started</h2>
  <p>Industry: <strong>{request.Industry}</strong></p>
  <p>Color Scheme: <strong>{request.ColorScheme}</strong></p>
  {(request.IncludeContactForm ? "<p><strong>✓ Contact Form Included</strong></p>" : "")}
</section>

<footer style='background: #2d3748; color: white; padding: 20px; text-align: center;'>
  <p>&copy; 2025 {request.ProjectName}. Generated by TechBirdsFly AI.</p>
</footer>";
    }

    private string GenerateDemoCss(GenerateWebsiteCommand request)
    {
        var colorMap = request.ColorScheme switch
        {
            "Blue" => "#3182ce",
            "Orange" => "#ed8936",
            "Green" => "#38a169",
            "Pink" => "#ed64a6",
            _ => "#667eea"
        };

        return $@"
* {{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}}

body {{
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  line-height: 1.6;
  color: #2d3748;
}}

h1, h2, h3 {{
  color: {colorMap};
}}

a {{
  color: {colorMap};
  text-decoration: none;
}}

button {{
  background-color: {colorMap};
  color: white;
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}}

button:hover {{
  opacity: 0.9;
}}";
    }
}
