using MediatR;
using TechBirdsFly.EditorService.Application.Features.CreateSection;
using TechBirdsFly.EditorService.Infrastructure;
using TechBirdsFly.EditorService.Infrastructure.AI;

var builder = WebApplication.CreateBuilder(args);

// Logging
builder.Logging.ClearProviders();
builder.Logging.AddConsole();

// Services
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// MediatR
builder.Services.AddMediatR(typeof(CreateSectionCommand));

// Infrastructure
builder.Services.AddInfrastructure(builder.Configuration);

// Temporary Llama Client for testing (replace with real implementation)
builder.Services.AddScoped<ILlamaClient, MockLlamaClient>();

// CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll",
        policy => policy.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("AllowAll");
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

// Create database on startup
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<TechBirdsFly.EditorService.Infrastructure.Persistence.EditorDbContext>();
    await db.Database.EnsureCreatedAsync();
}

app.Run();

// Mock Llama Client for development
public class MockLlamaClient : ILlamaClient
{
    private readonly ILogger<MockLlamaClient> _logger;

    public MockLlamaClient(ILogger<MockLlamaClient> logger)
    {
        _logger = logger;
    }

    public async Task<string> GenerateAsync(string prompt)
    {
        _logger.LogInformation("Mock Llama generating content");
        await Task.Delay(500); // Simulate delay
        return $@"
<section class='py-12 px-6 bg-gradient-to-r from-blue-500 to-purple-600'>
    <div class='max-w-4xl mx-auto'>
        <h2 class='text-3xl font-bold text-white mb-4'>Regenerated Section</h2>
        <p class='text-white text-lg'>This section was regenerated by AI with improved styling.</p>
    </div>
</section>
";
    }
}
