/**
 * Two-Factor Authentication (2FA) Utilities
 * ============================================================================
 * Handles TOTP (Time-based One-Time Password) 2FA including:
 * - QR code generation for authenticator apps
 * - TOTP verification
 * - Backup codes generation
 * - 2FA setup and verification flows
 * 
 * Note: This is client-side, server must validate TOTP codes
 */

// Local storage keys
const TFA_SETUP_KEY = '2fa_setup_temp';
const MAX_TOTP_ATTEMPTS = 3;
const TOTP_ATTEMPT_WINDOW = 60 * 60 * 1000; // 1 hour in ms
const TOTP_STEP = 30; // Google Authenticator uses 30-second time windows
const TOTP_DIGITS = 6;

/**
 * Generate a base32-encoded secret for TOTP
 * (Normally generated by server, but this helps with testing)
 */
export function generateTOTPSecret(length: number = 32): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

/**
 * Generate QR code data URL for TOTP setup
 * Format: otpauth://totp/Label?secret=SECRET&issuer=Issuer
 */
export function generateTOTPQRCodeURL(
  secret: string,
  email: string,
  issuer: string = 'TechBirdsFly'
): string {
  const encodedEmail = encodeURIComponent(email);
  const encodedIssuer = encodeURIComponent(issuer);
  const otpauthURL = `otpauth://totp/${encodedIssuer}:${encodedEmail}?secret=${secret}&issuer=${encodedIssuer}`;
  
  // Use QR code API endpoint - replace with your actual QR code service
  return `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(otpauthURL)}`;
}

/**
 * Generate backup codes for 2FA recovery
 * Returns 10 codes in format: XXXX-XXXX-XXXX
 */
export function generateBackupCodes(count: number = 10): string[] {
  const codes: string[] = [];
  
  for (let i = 0; i < count; i++) {
    let code = '';
    for (let j = 0; j < 12; j++) {
      code += Math.floor(Math.random() * 16).toString(16).toUpperCase();
    }
    // Format as XXXX-XXXX-XXXX
    codes.push(
      code.substring(0, 4) +
      '-' +
      code.substring(4, 8) +
      '-' +
      code.substring(8, 12)
    );
  }
  
  return codes;
}

/**
 * Store 2FA setup data temporarily (before server confirmation)
 */
export function store2FASetupData(setupData: {
  secret: string;
  qrCodeURL: string;
  backupCodes: string[];
  email: string;
}): void {
  if (typeof window === 'undefined') return;
  sessionStorage.setItem(TFA_SETUP_KEY, JSON.stringify(setupData));
}

/**
 * Retrieve temporarily stored 2FA setup data
 */
export function get2FASetupData(): {
  secret: string;
  qrCodeURL: string;
  backupCodes: string[];
  email: string;
} | null {
  if (typeof window === 'undefined') return null;
  const data = sessionStorage.getItem(TFA_SETUP_KEY);
  return data ? JSON.parse(data) : null;
}

/**
 * Clear temporary 2FA setup data
 */
export function clear2FASetupData(): void {
  if (typeof window === 'undefined') return;
  sessionStorage.removeItem(TFA_SETUP_KEY);
}

/**
 * Check if user has exceeded TOTP verification attempts
 */
export function check2FAAttempts(): {
  canVerify: boolean;
  attemptsRemaining: number;
  lockoutUntil?: Date;
} {
  if (typeof window === 'undefined') {
    return { canVerify: true, attemptsRemaining: MAX_TOTP_ATTEMPTS };
  }

  const attemptsStr = sessionStorage.getItem('2fa_attempts');
  const timestampStr = sessionStorage.getItem('2fa_timestamp');

  if (!attemptsStr || !timestampStr) {
    return { canVerify: true, attemptsRemaining: MAX_TOTP_ATTEMPTS };
  }

  const attempts = parseInt(attemptsStr);
  const timestamp = parseInt(timestampStr);
  const now = Date.now();

  // Check if lockout window has expired
  if (now - timestamp > TOTP_ATTEMPT_WINDOW) {
    sessionStorage.removeItem('2fa_attempts');
    sessionStorage.removeItem('2fa_timestamp');
    return { canVerify: true, attemptsRemaining: MAX_TOTP_ATTEMPTS };
  }

  // Check if user has exceeded attempts
  if (attempts >= MAX_TOTP_ATTEMPTS) {
    const lockoutUntil = new Date(timestamp + TOTP_ATTEMPT_WINDOW);
    return {
      canVerify: false,
      attemptsRemaining: 0,
      lockoutUntil,
    };
  }

  return {
    canVerify: true,
    attemptsRemaining: MAX_TOTP_ATTEMPTS - attempts,
  };
}

/**
 * Record a 2FA verification attempt
 */
export function record2FAAttempt(): void {
  if (typeof window === 'undefined') return;

  const attemptsStr = sessionStorage.getItem('2fa_attempts');
  const attempts = attemptsStr ? parseInt(attemptsStr) + 1 : 1;

  sessionStorage.setItem('2fa_attempts', attempts.toString());
  sessionStorage.setItem('2fa_timestamp', Date.now().toString());
}

/**
 * Clear 2FA attempts
 */
export function clear2FAAttempts(): void {
  if (typeof window === 'undefined') return;
  sessionStorage.removeItem('2fa_attempts');
  sessionStorage.removeItem('2fa_timestamp');
}

/**
 * Validate TOTP code format
 */
export function isValidTOTPCode(code: string): boolean {
  return /^\d{6}$/.test(code);
}

/**
 * Validate backup code format
 */
export function isValidBackupCode(code: string): boolean {
  return /^[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}$/.test(code.toUpperCase());
}

/**
 * Format backup code for display
 */
export function formatBackupCodeForDisplay(code: string): string {
  return code.toUpperCase();
}

/**
 * Generate a temporary 2FA session token (for storing which step of setup user is on)
 */
export function generate2FASessionToken(): string {
  return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
}

export type TwoFactorSetupData = {
  secret: string;
  qrCodeURL: string;
  backupCodes: string[];
  email: string;
};

export type TwoFactorAttemptCheck = {
  canVerify: boolean;
  attemptsRemaining: number;
  lockoutUntil?: Date;
};
