using System;

namespace ImageService.Domain.Events;

/// <summary>
/// Base class for domain events
/// </summary>
public abstract record DomainEvent
{
    public Guid AggregateId { get; init; }
    public DateTime OccurredAt { get; init; } = DateTime.UtcNow;
}

/// <summary>
/// Event raised when image is uploaded
/// </summary>
public record ImageUploadedEvent : DomainEvent
{
    public required string FileName { get; init; }
    public required string StoragePath { get; init; }
    public required long FileSizeBytes { get; init; }
    public required Guid UploadedByUserId { get; init; }
}

/// <summary>
/// Event raised when image is generated by AI
/// </summary>
public record ImageGeneratedEvent : DomainEvent
{
    public required string FileName { get; init; }
    public required string Prompt { get; init; }
    public required Guid GeneratedByUserId { get; init; }
}

/// <summary>
/// Event raised when image processing starts
/// </summary>
public record ImageProcessingStartedEvent : DomainEvent
{
    public required string ProcessingType { get; init; }
}

/// <summary>
/// Event raised when image becomes available
/// </summary>
public record ImageAvailableEvent : DomainEvent
{
    public required string CdnUrl { get; init; }
    public required int Width { get; init; }
    public required int Height { get; init; }
}

/// <summary>
/// Event raised when image processing fails
/// </summary>
public record ImageProcessingFailedEvent : DomainEvent
{
    public required string ErrorMessage { get; init; }
}

/// <summary>
/// Event raised when image is archived
/// </summary>
public record ImageArchivedEvent : DomainEvent
{
    public required Guid ArchivedByUserId { get; init; }
}

/// <summary>
/// Event raised when image metadata is updated
/// </summary>
public record ImageMetadataUpdatedEvent : DomainEvent
{
    public required string MetadataType { get; init; }
    public required string NewValue { get; init; }
}

/// <summary>
/// Event raised when image is deleted
/// </summary>
public record ImageDeletedEvent : DomainEvent
{
    public required Guid DeletedByUserId { get; init; }
}
