using System.IO.Compression;
using System.Text;

namespace GeneratorService.Services
{
    public interface IGeneratorService
    {
        Task<string> GenerateWebsiteCodeAsync(string prompt);
        Task<byte[]> PackageProjectAsZipAsync(string projectName, string generatedCode);
    }

    public class GeneratorService : IGeneratorService
    {
        private readonly ILogger<GeneratorService> _logger;

        public GeneratorService(ILogger<GeneratorService> logger)
        {
            _logger = logger;
        }

        /// <summary>
        /// Mock Azure OpenAI integration. Replace with real API call later.
        /// </summary>
        public async Task<string> GenerateWebsiteCodeAsync(string prompt)
        {
            _logger.LogInformation("Generating website code for prompt: {Prompt}", prompt);

            // Simulate API call delay
            await Task.Delay(1000);

            // Mock response: a simple React landing page
            var mockCode = GenerateMockReactComponent(prompt);
            return mockCode;
        }

        /// <summary>
        /// Package generated code and assets into a ZIP file.
        /// </summary>
        public async Task<byte[]> PackageProjectAsZipAsync(string projectName, string generatedCode)
        {
            _logger.LogInformation("Packaging project {ProjectName} as ZIP", projectName);

            using var memoryStream = new MemoryStream();
            using (var archive = new ZipArchive(memoryStream, ZipArchiveMode.Create, true))
            {
                // Add React component file
                var componentEntry = archive.CreateEntry($"{projectName}/src/App.tsx");
                using (var writer = new StreamWriter(componentEntry.Open()))
                {
                    await writer.WriteAsync(generatedCode);
                }

                // Add package.json
                var packageJsonEntry = archive.CreateEntry($"{projectName}/package.json");
                using (var writer = new StreamWriter(packageJsonEntry.Open()))
                {
                    var packageJson = GenerateMockPackageJson(projectName);
                    await writer.WriteAsync(packageJson);
                }

                // Add README
                var readmeEntry = archive.CreateEntry($"{projectName}/README.md");
                using (var writer = new StreamWriter(readmeEntry.Open()))
                {
                    var readme = GenerateMockReadme(projectName);
                    await writer.WriteAsync(readme);
                }

                // Add .gitignore
                var gitignoreEntry = archive.CreateEntry($"{projectName}/.gitignore");
                using (var writer = new StreamWriter(gitignoreEntry.Open()))
                {
                    await writer.WriteAsync("node_modules/\n.env\nbuild/\ndist/\n");
                }
            }

            memoryStream.Position = 0;
            return memoryStream.ToArray();
        }

        private string GenerateMockReactComponent(string prompt)
        {
            return $@"import React from 'react';
import './App.css';

export default function App() {{
  return (
    <div className='container'>
      <header>
        <h1>Welcome to Your AI-Generated Website</h1>
        <p>Generated for: {prompt}</p>
      </header>
      <main>
        <section className='hero'>
          <h2>Your Content Here</h2>
          <p>This website was generated using AI based on your prompt:</p>
          <blockquote>""{prompt}""</blockquote>
        </section>
        <section className='features'>
          <h3>Features</h3>
          <ul>
            <li>Modern React-based architecture</li>
            <li>Responsive Tailwind CSS styling</li>
            <li>Ready to deploy</li>
            <li>Fully customizable</li>
          </ul>
        </section>
        <footer>
          <p>© 2025 TechBirdsFly.AI - Powered by AI</p>
        </footer>
      </main>
    </div>
  );
}}";
        }

        private string GenerateMockPackageJson(string projectName)
        {
            return @$"{{
  ""name"": ""{projectName}"",
  ""version"": ""1.0.0"",
  ""description"": ""AI-generated website"",
  ""dependencies"": {{
    ""react"": ""^18.0.0"",
    ""react-dom"": ""^18.0.0"",
    ""tailwindcss"": ""^3.4.0""
  }},
  ""scripts"": {{
    ""start"": ""react-scripts start"",
    ""build"": ""react-scripts build"",
    ""test"": ""react-scripts test""
  }}
}}";
        }

        private string GenerateMockReadme(string projectName)
        {
            return $@"# {projectName}

This project was generated by **TechBirdsFly.AI** - an intelligent website generator.

## Getting Started

### Prerequisites
- Node.js 16+
- npm or yarn

### Installation

```bash
npm install
```

### Running Locally

```bash
npm start
```

The app will open at [http://localhost:3000](http://localhost:3000).

### Building for Production

```bash
npm run build
```

## Customization

Edit the React components in `src/` to customize your website.

## Deployment

Deploy to Vercel, Azure Static Web Apps, or your preferred hosting platform.

---
Generated by **TechBirdsFly.AI** | [https://techbirdsfly.ai](https://techbirdsfly.ai)
";
        }
    }
}
